services:
  front-end:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - back-end
    networks:
      - laravel

  back-end:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - data-base
    networks:
      - laravel

  data-base:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: conta_certa_db 
      MYSQL_USER: pi
      MYSQL_PASSWORD: pi
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  
    networks:
      - laravel
    volumes:
      - ./.docker/db_data/bd:/var/lib/mysql # Persistência de dados do banco de dados.
      - ./.docker/db_data/sql:/docker-entrypoint-initdb.d # Script para criar tabelas.

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9090:9090"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
