services:
  php:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/app
    networks:
      - laravel
    depends_on:
      - db-api-sistemafinanceiro

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - laravel

  db-api-sistemafinanceiro:
    container_name: mysql
    image: mysql
    volumes:
      - .docker/db_data:/var/lib/mysql
    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    
    ports:
      - "3307:3306"  
    networks:
      - laravel

  phpmyadmin-api-sistemafinanceiro:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db-api-sistemafinanceiro
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "9999:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
